-- ************************** SqlDBM: Databricks **************************
-- * Generated by SqlDBM: Databricks sample by kushal.mangtani@sqldbm.com *


-- * The 'delta.columnMapping.mode' property is added by default to make the alter script work correctly *

-- ************************************** Dim_Supplier

CREATE TABLE Dim_Supplier
(
 SupplierId  bigint NOT NULL CONSTRAINT PK_Supplier_Id PRIMARY KEY,
 CompanyName string NOT NULL,
 Phone       string
)
USING DELTA
 PARTITIONED BY (CompanyName)
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Supplier
  FOR COLUMNS(SupplierId)
;



-- ************************************** Dim_Product

CREATE TABLE Dim_Product
(
 ProductId    bigint NOT NULL CONSTRAINT PK_Product_Id PRIMARY KEY,
 ProductName  string NOT NULL,
 IsDiscounted boolean NOT NULL
)
USING DELTA
 PARTITIONED BY (ProductName)
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Product
  FOR COLUMNS(ProductId)
;



-- ************************************** Dim_Order

CREATE TABLE Dim_Order
(
 OrderId       bigint NOT NULL CONSTRAINT PK_Dim_Order PRIMARY KEY,
 OrderNumber   string NOT NULL,
 OrderQuantity int NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Order
  FOR COLUMNS(OrderId)
;



-- ************************************** Dim_Customer

CREATE TABLE Dim_Customer
(
 CustomerId   bigint NOT NULL COMMENT 'Unique identifier for customer' CONSTRAINT PK_Dim_Customer PRIMARY KEY,
 CustomerName string NOT NULL,
 Phone        string
)
USING DELTA
 PARTITIONED BY (CustomerName)
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Simple');

CREATE BLOOMFILTER INDEX
  ON TABLE Dim_Customer
  FOR COLUMNS(CustomerId)
;



-- ************************************** Fact_Customer_Orders

CREATE TABLE Fact_Customer_Orders
(
 OrderId    bigint NOT NULL CONSTRAINT FK_4 REFERENCES Dim_Order,
 CustomerId bigint NOT NULL CONSTRAINT FK_3 REFERENCES Dim_Customer,
 ProductId  bigint NOT NULL CONSTRAINT FK_6 REFERENCES Dim_Product,
 SupplierId bigint NOT NULL CONSTRAINT FK_5 REFERENCES Dim_Supplier,
 Price      decimal NOT NULL,
 Quantity   int NOT NULL,
 Profit     bigint NOT NULL,
 Date       date NOT NULL,
 CONSTRAINT PK_6 PRIMARY KEY (OrderId, CustomerId, ProductId, SupplierId)
)
USING DELTA
 TBLPROPERTIES (delta.columnMapping.mode = 'name', Type = 'Complex');

ALTER TABLE Fact_Customer_Orders ADD CONSTRAINT Check_1 CHECK (Date < '2021-07-01');
ALTER TABLE Fact_Customer_Orders ADD CONSTRAINT Check_2 CHECK (Quantity < 100);


CREATE BLOOMFILTER INDEX
  ON TABLE Fact_Customer_Orders
  FOR COLUMNS(Profit)
;


